# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Leitura Psi
email: jimpsicologia@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper mollis velit id fermentum. Donec ipsum tellus, fringilla sagittis massa porttitor, porttitor malesuada tellus. Nullam faucibus vulputate metus in commodo. Aenean eu felis non nibh consectetur efficitur lacinia sit amet dui. Ut consequat dui vel sem faucibus, at malesuada mi cursus. Etiam sagittis metus at aliquam pharetra. Nunc eu velit feugiat, consequat elit ac, fringilla nisi. Vestibulum vehicula enim id interdum imperdiet. Etiam id leo at nisi luctus rhoncus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JuPsi.com.br" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: psicologajulianamartins
instagram_username: psicologajulianamartins
linkedin_username: psicologajulianamartins
twitter_username: psicologajulianamartins

# Build settings
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled: all
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/categoria/:name/'
  slug_mode: latin

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
